"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var extension_shell_metadata_1 = require("./extension-shell.metadata");
exports.ExtensionShellMetadata = extension_shell_metadata_1.ExtensionShellMetadata;
var page_metadata_1 = require("./page.metadata");
exports.PageMetadata = page_metadata_1.PageMetadata;
var page_form_metadata_1 = require("./page-form.metadata");
exports.PageFormMetadata = page_form_metadata_1.PageFormMetadata;
var page_schema_metadata_1 = require("./page-schema.metadata");
exports.PageSchemaMetadata = page_schema_metadata_1.PageSchemaMetadata;
