declare module 'jss-preset-default'
declare module 'react-jss/*'
declare module 'recompose/*'
declare module 'react-dnd-html5-backend'
declare module 'react-dnd-touch-backend'
declare module 'rc-color-picker'
declare module 'react-swipeable-views'
declare module 'react-swipeable-views-utils'
declare module 'react-dazzle';
declare module 'bizcharts';
declare module '@antv/data-set';
declare module 'react-web-cascader'
