"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var addon_module_1 = require("./addon.module");
exports.AddonModule = addon_module_1.AddonModule;
var extension__module_1 = require("./extension. module");
exports.ExtensionModule = extension__module_1.ExtensionModule;
var injection_module_1 = require("./injection.module");
exports.InjectionModule = injection_module_1.InjectionModule;
var module_module_1 = require("./module.module");
exports.ModuleModule = module_module_1.ModuleModule;
